version: '3.8'

services:
  note-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - note-backend

  note-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-note-db}
      - DB_PORT=5432
      - DB_NAME=dhx
      - DB_USER=postgres
      - DB_PASSWORD=password123
    command: npm run start:${NODE_ENV:-prod}
    depends_on:
      - note-db

  note-db:
    build:
      context: ./database
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dhx
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default: